/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/reseaux/raccordements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Récupère la liste des dossiers de raccordement. */
        get: operations["Raccordement_lister"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reseaux/raccordements/manquants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Récupère la liste des projets sans dossier de raccordement. */
        get: operations["Raccordement_listerManquants"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/laureats/{identifiantProjet}/raccordements/{reference}/mise-en-service": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Transmet la date de mise en service pour un dossier de raccordement.
         *
         *     _NB: un projet peut avoir plusieurs dossiers de raccordement._
         */
        post: operations["Raccordement_transmettreMiseEnService"];
        delete?: never;
        options?: never;
        head?: never;
        /**
         * @description Transmet la date de mise en service pour un dossier de raccordement.
         *
         *     _NB: un projet peut avoir plusieurs dossiers de raccordement._
         */
        patch: operations["Raccordement_modifierMiseEnService"];
        trace?: never;
    };
    "/laureats/{identifiantProjet}/raccordements/demande-complete-raccordement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Transmet une demande complète de raccordement */
        post: operations["Raccordement_transmettreDemandeCompl\u00E8te"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/laureats/{identifiantProjet}/raccordements/{reference}/demande-complete-raccordement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Modifie la demande complète de raccordement */
        patch: operations["Raccordement_modifierDemandeCompl\u00E8te"];
        trace?: never;
    };
    "/achevements/a-transmettre": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Récupère les projets en attente d'achèvement
         *
         *     _NB: Dans un premier temps, ce endpoint retourne tous les projets lauréats non achevés et non abandonnés. A terme, il sera remplacé par /achevements/en-attente-confirmation_
         */
        get: operations["AchevementV1_listerProjetAvecAchevementATransmettre"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/laureats/{identifiantProjet}/achevement/date-achevement": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Transmettre la date d'achèvement d'un projet
         *
         *     _NB: A terme, ce endpoint sera retiré_ et remplacé par /laureats/{identifiantProjet}/achevement/confirmer_
         */
        post: operations["AchevementV1_transmettreDateDAchevement"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Addresse: {
            adresse1: string;
            adresse2: string;
            codePostal: string;
            commune: string;
            departement: string;
            region: string;
        };
        /**
         * @description Un dossier de raccordement représente un point d'injection d'un projet.
         *
         *     _NB: un projet peut avoir plusieurs dossiers de raccordement._
         */
        DossierRaccordement: {
            identifiantProjet: string;
            nomProjet: string;
            appelOffre: string;
            periode: string;
            famille: string;
            /** @description Adresse complète du site de production */
            siteDeProduction: components["schemas"]["Addresse"];
            numeroCRE: string;
            referenceDossier: string;
            /** @enum {string} */
            statut: "actif" | "achevé";
            /** Format: float */
            puissance: number;
            unitePuissance: string;
            nomCandidat: string;
            societeMere: string;
            emailContact: string;
            /**
             * Format: date
             * @description La date où le projet a été notifié
             */
            dateNotification: string;
        };
        RangeOptions: {
            /** Format: uint16 */
            startPosition: number;
            /** Format: uint16 */
            endPosition: number;
        };
        Error: {
            message: string;
        };
        MiseEnServiceBody: {
            /** Format: date */
            dateMiseEnService: string;
        };
        MiseEnServiceBodyMergePatchCreateOrUpdate: {
            /** Format: date */
            dateMiseEnService?: string;
        };
        TransmettreDemandeCompleteRaccordementBody: {
            reference: string;
            /** Format: date */
            dateAccuseReception: string;
        };
        ModifierDemandeCompleteBodyMergePatchCreateOrUpdate: {
            nouvelleReference?: string;
        };
        ProjetAvecAchevementATransmettre: {
            identifiantProjet: string;
            appelOffre: string;
            periode: string;
            nomProjet: string;
            siteDeProduction: components["schemas"]["Addresse"];
            /**
             * Format: date
             * @description La date où le projet a été notifié
             */
            dateNotification: string;
            /**
             * @description L'identifiant du gestionnaire de réseau gérant le raccordement du projet.
             *     Tous les dossiers d'un même projet sont gérés par le même gestionnaire de réseau.
             */
            identifiantGestionnaireReseau: string;
            /**
             * @description La référence du dossier de raccordement.
             *     Un projet peut avoir plusieurs dossiers de raccordement (une ligne = un dossier)
             */
            referenceDossierRaccordement: string;
            /**
             * Format: date
             * @description La date de qualification de la Demande Complète de Raccordement.
             */
            dateDCR?: string;
            /**
             * Format: float
             * @description Prix de vente, en € par MWh
             */
            prix: number;
            /** @description Indique si le porteur de projet a choisi d'appliquer le coefficient K, afin d'indexer le prix sur l'inflation */
            coefficientKChoisi: boolean;
            /**
             * Format: float
             * @description Puissance actuelle du projet, en MW
             */
            puissance: number;
            /**
             * Format: float
             * @description Puissance du projet à la candidature, en MW
             */
            puissanceInitiale: number;
        };
        TransmettreDateAchevementBody: {
            /** Format: date */
            dateAchevement: string;
        };
    };
    responses: never;
    parameters: {
        "DossierRaccordementParameters.identifiantProjet": string;
        "DossierRaccordementParameters.reference": string;
        LaureatParameters: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Raccordement_lister: {
        parameters: {
            query?: {
                /** @description L'index du dernier élément (`endPosition`) de la page précédente. */
                after?: number;
                /** @description Ne lister que les dossier de raccordement avec, ou sans, date de mise en service. */
                avecDateMiseEnService?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["DossierRaccordement"][];
                        range: components["schemas"]["RangeOptions"];
                        /** Format: uint16 */
                        total: number;
                    };
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    Raccordement_listerManquants: {
        parameters: {
            query?: {
                /** @description L'index du dernier élément (`endPosition`) de la page précédente. */
                after?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["DossierRaccordement"][];
                        range: components["schemas"]["RangeOptions"];
                        /** Format: uint16 */
                        total: number;
                    };
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    Raccordement_transmettreMiseEnService: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifiantProjet: components["parameters"]["DossierRaccordementParameters.identifiantProjet"];
                reference: components["parameters"]["DossierRaccordementParameters.reference"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MiseEnServiceBody"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    Raccordement_modifierMiseEnService: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifiantProjet: components["parameters"]["DossierRaccordementParameters.identifiantProjet"];
                reference: components["parameters"]["DossierRaccordementParameters.reference"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["MiseEnServiceBodyMergePatchCreateOrUpdate"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    "Raccordement_transmettreDemandeCompl\u00E8te": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifiantProjet: components["parameters"]["LaureatParameters"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransmettreDemandeCompleteRaccordementBody"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    "Raccordement_modifierDemandeCompl\u00E8te": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifiantProjet: components["parameters"]["DossierRaccordementParameters.identifiantProjet"];
                reference: components["parameters"]["DossierRaccordementParameters.reference"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/merge-patch+json": components["schemas"]["ModifierDemandeCompleteBodyMergePatchCreateOrUpdate"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    AchevementV1_listerProjetAvecAchevementATransmettre: {
        parameters: {
            query?: {
                /** @description L'index du dernier élément (`endPosition`) de la page précédente. */
                after?: number;
                appelOffre?: string;
                periode?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["ProjetAvecAchevementATransmettre"][];
                        range: components["schemas"]["RangeOptions"];
                        /** Format: uint16 */
                        total: number;
                    };
                };
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    AchevementV1_transmettreDateDAchevement: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                identifiantProjet: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransmettreDateAchevementBody"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description An unexpected error response. */
            default: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
